Exercise 3:

In [3]:
import pandas as pd
# Create a pandas Series from the list and display it
data = [10, 64, 21, 3, 5]
pd.Series(data)

0    10
1    64
2    21
3     3
4     5
dtype: int64

In [11]:
# Create a Series with numpy array and display it 
import numpy as np
np_array = np.array([5, 2, 3])
pd.Series(np_array)

0    5
1    2
2    3
dtype: int64

Exercise 4:

In [28]:
# Create a Series of 0, 10, 20, 30, …, 90, 100 as float and display it 
pd.Series(np.arange(0, 101, 10)).astype('float64')

0       0.0
1      10.0
2      20.0
3      30.0
4      40.0
5      50.0
6      60.0
7      70.0
8      80.0
9      90.0
10    100.0
dtype: float64

Exercise 5: 
What’s the content and dtype of the following Series? 
pd.Series(np.linspace(3, 27, 3))

In [6]:
pd.Series(np.linspace(3, 27, 3))

0     3.0
1    15.0
2    27.0
dtype: float64

Exercise 6: 
What’s the content and dtype of the following Series? 
pd.Series(np.linspace(3, 27, 3))

In [7]:
s=pd.Series(np.linspace(3, 27, 3))
print("Data type=",s.dtype)
print(s.info())

Data type= float64
<class 'pandas.core.series.Series'>
RangeIndex: 3 entries, 0 to 2
Series name: None
Non-Null Count  Dtype
--------------  -----
3 non-null      float64
dtypes: float64(1)
memory usage: 156.0 bytes
None

Exercise 7:
Task 1:
Create a DataFrame with these lists and corresponding column labels: 'Label', 'Name', 'Age', 'Country', and display it

In [4]:
labels = ['a', 'b', 'c', 'd', 'e', 'f'] 
names = ['Mia', 'Ana', 'Luke', 'Charlie', 'Chloe', 'Robert'] 
ages = [25, 30, 35, 21, 32, 28] 
countries = ['Singapore', 'China', 'Nigeria', 'France', 'France', 'Italy']
df = pd.DataFrame({ 
'Label': labels, 
'Name': names, 
'Age': ages, 
'Country': countries 
})
df

  Label     Name  Age    Country
0     a      Mia   25  Singapore
1     b      Ana   30      China
2     c     Luke   35    Nigeria
3     d  Charlie   21     France
4     e    Chloe   32     France
5     f   Robert   28      Italy

Task 2 
What’re the default index values to each row?

In [ ]:
# 0 1 2 3 4

Task 3 
How does the following line of code affect the DataFrame?  
df.set_index('Label', inplace=True)

In [8]:
df.set_index('Label', inplace=True)
df

          Name  Age    Country  Salary
Label
a          Mia   25  Singapore    50.0
b          Ana   30      China    28.0
c         Luke   35    Nigeria    68.4
d      Charlie   21     France    45.3
e        Chloe   32     France    80.2
f       Robert   28      Italy    34.0

Task 4 
add a new column 'Grade' [11, 9, 7, 5, 4, 6] to the DataFrame

In [30]:
print(df.columns)
df['Grade'] = [11, 9, 7, 5, 4, 6] # direct assignment. Create the column by assigning a list, Series to a new column name 
#(or) 
#df.insert(len(df.columns), 'Grade', [11, 9, 7, 5, 4, 6]) # Insert at the last column 
df

Index(['Name', 'Age', 'Country', 'Salary', 'Grade', 'Management Level'], dtype='object')

          Name  Age    Country  Salary  Grade Management Level
Label
c         Luke   35    Nigeria  51.000     11           Middle
e        Chloe   32     France  29.400      9        Operative
b          Ana   30      China  69.768      7           Middle
f       Robert   28      Italy  46.206      5           Middle
a          Mia   25  Singapore  81.804      4              Top
d      Charlie   21     France  35.700      6           Middle

Task 5 
add a new column 'Management Level' with three different levels 'Top' 'Middle' 'Operative, conditional on the column 'Grade' 
Grade 10 or above is 'Top', Grade 5 to 9 inclusive is 'Middle', and Grade 4 or under is 'Operative'

In [12]:
df['Management Level']=np.random.choice(['Top','Middle','Operative'],size=6)
df

          Name  Age    Country  Salary  Grade Management Level
Label
a          Mia   25  Singapore    50.0     11              Top
b          Ana   30      China    28.0      9           Middle
c         Luke   35    Nigeria    68.4      7           Middle
d      Charlie   21     France    45.3      5           Middle
e        Chloe   32     France    80.2      4        Operative
f       Robert   28      Italy    34.0      6        Operative

In [13]:
# Define a function to determine management level based on grade 
def determine_management_level(grade): 
    if grade >= 10: 
        return 'Top' 
    elif 5 <= grade <= 9: 
        return 'Middle' 
    else: 
        return 'Operative' 
 
# Apply the function to the 'Grade' column to create the new 'Management Level' column 
df['Management Level'] = df['Grade'].apply(determine_management_level)
df

          Name  Age    Country  Salary  Grade Management Level
Label
a          Mia   25  Singapore    50.0     11              Top
b          Ana   30      China    28.0      9           Middle
c         Luke   35    Nigeria    68.4      7           Middle
d      Charlie   21     France    45.3      5           Middle
e        Chloe   32     France    80.2      4        Operative
f       Robert   28      Italy    34.0      6           Middle

Task 6 
# Sort the DataFrame by 'Age' in descending order

In [14]:
# Sort the DataFrame by 'Age' in ascending order 
df.sort_values(by=['Age'], ascending=False, inplace=True)
df

          Name  Age    Country  Salary  Grade Management Level
Label
c         Luke   35    Nigeria    68.4      7           Middle
e        Chloe   32     France    80.2      4        Operative
b          Ana   30      China    28.0      9           Middle
f       Robert   28      Italy    34.0      6           Middle
a          Mia   25  Singapore    50.0     11              Top
d      Charlie   21     France    45.3      5           Middle

Task 7 
# add a new column 'Salary' (k) to the DataFrame df 
df['Salary'] = [50, 28, 68.4, 45.3, 80.2, 34] 
Check out the updated DataFrame. 
Now it comes to the pay rise, anyone graded 6 or above receive a 2% salary rise and anyone 
graded 5 or below receives a 5% salary rise. Can you update it in the dataset?

In [15]:
df['Salary'] = [50, 28, 68.4, 45.3, 80.2, 34]
df

          Name  Age    Country  Salary  Grade Management Level
Label
c         Luke   35    Nigeria    50.0      7           Middle
e        Chloe   32     France    28.0      4        Operative
b          Ana   30      China    68.4      9           Middle
f       Robert   28      Italy    45.3      6           Middle
a          Mia   25  Singapore    80.2     11              Top
d      Charlie   21     France    34.0      5           Middle

In [16]:
df['Salary'] = df.apply(lambda row: row['Salary'] * 1.02 if row['Grade'] >= 6 else row['Salary'] * 1.05, axis=1)
df

          Name  Age    Country  Salary  Grade Management Level
Label
c         Luke   35    Nigeria  51.000      7           Middle
e        Chloe   32     France  29.400      4        Operative
b          Ana   30      China  69.768      9           Middle
f       Robert   28      Italy  46.206      6           Middle
a          Mia   25  Singapore  81.804     11              Top
d      Charlie   21     France  35.700      5           Middle

(or)
Applying pay rise based on the grade 2% rise for grades 6 and above, 5% rise for grades 5 and below 
df.loc[df['Grade'] >= 6, 'Salary'] *= 1.02  # 2% increase 
df.loc[df['Grade'] <= 5, 'Salary'] *= 1.05  # 5% increase 

(or)
def apply_raise(row): 
    if row['Grade'] >= 6: 
        return row['Salary'] * 1.02  # 2% increase 
    else: 
        return row['Salary'] * 1.05  # 5% increase 
Applying the raise using the apply function 
df['Salary'] = df.apply(apply_raise, axis=1)

Task 8 
Pandas also offers a range of statistical functions including sum(), mean(), mode(), std(). Look up and make some notes. Then run the following code to see the output, make sure you understand how each works.
# Applying statistical functions 
total_salary = df['Salary'].sum() 
average_age = df['Age'].mean() 
common_age = df['Age'].mode()[0]  # Mode returns multiple values in this case, so 
take the first one 
salary_std_dev = df['Salary'].std()

In [32]:
total_salary = df['Salary'].sum()
print(total_salary)
average_age = df['Age'].mean()
print(average_age)
common_age = df['Age'].mode()[0] # Mode returns multiple values in this case, so take the first one
print(common_age)
salary_std_dev = df['Salary'].std()
print(salary_std_dev)

313.878
28.5
21
20.07193494409545

Task 9 
Can you apply these statistical functions to the columns ‘Age’, ‘Grade’, and ‘Salary’?

In [22]:
# Applying statistical functions to 'Age', 'Grade', and 'Salary' 
age_stats = df['Age'].agg(['sum', 'mean', 'std'])
print(age_stats)

grade_stats = df['Grade'].agg(['sum', 'mean', 'std']) 
print(grade_stats)

salary_stats = df['Salary'].agg(['sum', 'mean', 'std'])
print(salary_stats)

sum     171.00000
mean     28.50000
std       5.00999
Name: Age, dtype: float64
sum     42.000000
mean     7.000000
std      2.607681
Name: Grade, dtype: float64
sum     313.878000
mean     52.313000
std      20.071935
Name: Salary, dtype: float64

Task 10 
Calculate the average ‘Age’, ‘Salary’, and ‘Grade’ for each management level.  
Hint: using groupby()

In [23]:
grouped_df = df.groupby('Management Level').agg({'Age': 'mean', 'Salary': 'mean', 'Grade': 'mean'})
grouped_df

                   Age   Salary  Grade
Management Level
Middle            28.5  50.6685   6.75
Operative         32.0  29.4000   4.00
Top               25.0  81.8040  11.00

In [ ]:
Task 11

In [24]:
num_summary_df = df[['Age', 'Salary', 'Grade']].describe()
num_summary_df

            Age     Salary      Grade
count   6.00000   6.000000   6.000000
mean   28.50000  52.313000   7.000000
std     5.00999  20.071935   2.607681
min    21.00000  29.400000   4.000000
25%    25.75000  38.326500   5.250000
50%    29.00000  48.603000   6.500000
75%    31.50000  65.076000   8.500000
max    35.00000  81.804000  11.000000

In [25]:
cat_summary_df = df[['Country', 'Management Level']].describe()
cat_summary_df

       Country Management Level
count        6                6
unique       5                3
top     France           Middle
freq         2                4

In [26]:
# Applying describe() on the entire DataFrame, including all columns (both numerical and categorical) 
all_summary_df = df.describe(include='all')
all_summary_df

        Name       Age Country     Salary      Grade Management Level
count      6   6.00000       6   6.000000   6.000000                6
unique     6       NaN       5        NaN        NaN                3
top     Luke       NaN  France        NaN        NaN           Middle
freq       1       NaN       2        NaN        NaN                4
mean     NaN  28.50000     NaN  52.313000   7.000000              NaN
std      NaN   5.00999     NaN  20.071935   2.607681              NaN
min      NaN  21.00000     NaN  29.400000   4.000000              NaN
25%      NaN  25.75000     NaN  38.326500   5.250000              NaN
50%      NaN  29.00000     NaN  48.603000   6.500000              NaN
75%      NaN  31.50000     NaN  65.076000   8.500000              NaN
max      NaN  35.00000     NaN  81.804000  11.000000              NaN